name: workflow
on:
  push:
    branches:
      - feature/*

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Welcome Title
        run: |
          echo "Curso DevSecOps"
          echo "Laboratorio Final"
      - name: Validating existence of project in Sonarcloud
        id: validate-project-sonar
        run: |
          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'organization=curso-seguridad-usach' -d 'project=${{ github.event.repository.name }}' -d 'visibility=public' 
          if [ $? -eq 0 ]; then
            echo "Proyecto creado exitosamente en Sonarcloud"
            curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
          else
            echo "Proyecto ya creado en Sonarcloud o error detectado durante la creación"
          fi
      - name: Validating project type
        run: |
        
          if [ -f "package.json" ]; then
            echo "Proyecto Node.js"
            echo "project_type=node.js" >> $GITHUB_ENV
            
          else
            echo "Tipo de proyecto no soportado"
            exit 1
          fi