name: Lab Final Workflow
on:
  push:
    branches:
      - feature/*

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Title
        run: |
          echo "Curso DevSecOps"
          echo "Laboratorio Final"
#      - name: Validating existence of project in Sonarcloud
#        id: validate-project-sonar
#        run: |
#          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'organization=curso-seguridad-usach' -d 'project=${{ github.event.repository.name }}' -d 'visibility=public' 
#          if [ $? -ne 0 ]; then
#            echo "Proyecto ya creado en Sonarcloud o error detectado durante la creación"
#          else
#            echo "Proyecto creado exitosamente en Sonarcloud"
#            curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
#          fi

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests with coverage
        run: npm run test -- --coverage
        
      - name: Validating project type
        id: validate-project-type
        run: |
        
          if [ -f "package.json" ]; then
            echo "Proyecto Node.js"
            echo "NODEJS=true" >> $GITHUB_ENV
          else
            echo "Tipo de proyecto no soportado"
            exit 1
          fi